# Generated by Django 5.2.3 on 2025-06-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_nl",
                    models.CharField(
                        max_length=200, verbose_name="Titel in Nederlands"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(max_length=200, verbose_name="Title in English"),
                ),
                (
                    "company_nl",
                    models.CharField(
                        max_length=200, verbose_name="Bedrijf in Nederlands"
                    ),
                ),
                (
                    "company_en",
                    models.CharField(max_length=200, verbose_name="Company in English"),
                ),
                (
                    "description_nl",
                    models.TextField(verbose_name="Beschrijving in Nederlands"),
                ),
                (
                    "description_en",
                    models.TextField(verbose_name="Description in English"),
                ),
                ("start_date", models.DateField(verbose_name="Startdatum")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Einddatum"),
                ),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="Huidige baan"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="logos/", verbose_name="Logo"
                    ),
                ),
            ],
        ),
    ]
