# Exported from Render on 2026-04-21T14:16:06Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: benteschopman
      runtime: python
      repo: https://github.com/B2TheEe/vibe_portfolio
      plan: starter
      envVars:
      - key: DJANGO_DEBUG
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PYTHON_VERSION
        sync: false
      - key: DJANGO_ADMIN_URL
        sync: false
      - key: SECURE_HSTS_SECONDS
        sync: false
      - key: CSRF_COOKIE_SECURE
        sync: false
      - key: SESSION_COOKIE_SECURE
        sync: false
      - key: SECURE_SSL_REDIRECT
        sync: false
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: DJANGO_SECRET_KEY
        sync: false
      region: frankfurt
      buildCommand: pip install -r requirements.txt
      startCommand: gunicorn vibe_portfolio.wsgi:application
      preDeployCommand: ./build.sh
      autoDeployTrigger: commit
