# Generated by Django 5.2.3 on 2025-06-28 14:21

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_nl",
                    models.CharField(max_length=100, verbose_name="Naam in Nederlands"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=100, verbose_name="Name in English"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_nl",
                    models.CharField(
                        max_length=200, verbose_name="Titel in Nederlands"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(max_length=200, verbose_name="Title in English"),
                ),
                (
                    "short_content_nl",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        verbose_name="Korte inhoud in Nederlands"
                    ),
                ),
                (
                    "short_content_en",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        verbose_name="Short content in English"
                    ),
                ),
                (
                    "content_nl",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        verbose_name="Inhoud in Nederlands"
                    ),
                ),
                (
                    "content_en",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        verbose_name="Content in English"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Aangemaakt op"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Bijgewerkt op"),
                ),
                (
                    "published_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Gepubliceerd op"
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog_main_images/",
                        verbose_name="Hoofd Afbeelding",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="app_Blog.category",
                        verbose_name="Categorie",
                    ),
                ),
            ],
        ),
    ]
