# Generated by Django 5.2.3 on 2025-06-26 19:57

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="blog_images/")),
            ],
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_nl",
                    models.CharField(
                        max_length=200, verbose_name="Titel in Nederlands"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(max_length=200, verbose_name="Title in English"),
                ),
                (
                    "content_nl",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        verbose_name="Inhoud in Nederlands"
                    ),
                ),
                (
                    "content_en",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        verbose_name="Content in English"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Aangemaakt op"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Bijgewerkt op"),
                ),
                (
                    "images",
                    models.ManyToManyField(
                        blank=True, to="app_Blog.blogimage", verbose_name="Afbeeldingen"
                    ),
                ),
            ],
        ),
    ]
