# Generated by Django 5.2.3 on 2025-06-28 14:59

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_Blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="category",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="content_en",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="content_nl",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="published_date",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="short_content_en",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="short_content_nl",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="title_nl",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blogpost",
            name="title",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="main_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="blog_main_images/"
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
