# Generated by Django 4.2.25 on 2026-04-14 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_Blog', '0002_remove_blogpost_category_remove_blogpost_content_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='app_Blog.category'),
        ),
    ]
