# Generated by Django 5.2.3 on 2025-06-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_Education", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="logos/", verbose_name="Logo"
            ),
        ),
    ]
