# Generated by Django 4.2.25 on 2025-10-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubproject',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='githubproject',
            old_name='title',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='githubproject',
            name='description_nl',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='githubproject',
            name='title_nl',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
