# Generated by Django 4.2.25 on 2026-04-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Skills', '0001_initial'),
        ('app_Portfolio', '0002_rename_description_githubproject_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubproject',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='projects', to='app_Skills.skill', verbose_name='Skills'),
        ),
    ]
