# Generated by Django 4.2.25 on 2026-05-06 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_Portfolio", "0003_githubproject_skills"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioItem",
            fields=[
                (
                    "githubproject_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app_Portfolio.githubproject",
                    ),
                ),
                ("url", models.URLField(verbose_name="Website URL")),
            ],
            options={
                "verbose_name": "Portfolio Item",
                "verbose_name_plural": "Portfolio Items",
            },
            bases=("app_Portfolio.githubproject",),
        ),
    ]
