# Generated by Django 5.2.3 on 2025-06-25 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_nl",
                    models.CharField(max_length=100, verbose_name="Naam in Nederlands"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=100, verbose_name="Name in English"),
                ),
                ("position", models.IntegerField(unique=True, verbose_name="Positie")),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_nl",
                    models.CharField(max_length=100, verbose_name="Naam in Nederlands"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=100, verbose_name="Name in English"),
                ),
                (
                    "description_nl",
                    models.TextField(verbose_name="Beschrijving in Nederlands"),
                ),
                (
                    "description_en",
                    models.TextField(verbose_name="Description in English"),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (1, "Poor"),
                            (2, "Average"),
                            (3, "Good"),
                            (4, "Very Good"),
                            (5, "Excellent"),
                        ],
                        default=3,
                        verbose_name="Niveau",
                    ),
                ),
                ("icon", models.ImageField(upload_to="icons/", verbose_name="Icoon")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="app_Skills.category",
                        verbose_name="Categorie",
                    ),
                ),
            ],
        ),
    ]
