# Generated by Django 5.2.3 on 2025-06-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutMe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_nl",
                    models.CharField(max_length=100, verbose_name="Title in Dutch"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=100, verbose_name="Title in English"),
                ),
                (
                    "description_nl",
                    models.TextField(verbose_name="Description in Dutch"),
                ),
                (
                    "description_en",
                    models.TextField(verbose_name="Description in English"),
                ),
                ("bio_nl", models.TextField(verbose_name="Bio in Dutch")),
                ("bio_en", models.TextField(verbose_name="Bio in English")),
                ("photo", models.ImageField(upload_to="photos/")),
                ("cv", models.FileField(upload_to="cv/")),
            ],
        ),
    ]
