# Generated by Django 5.2.3 on 2025-06-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_AboutMe", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutme",
            name="cv",
        ),
        migrations.AddField(
            model_name="aboutme",
            name="cv_en",
            field=models.FileField(
                blank=True, null=True, upload_to="cv/", verbose_name="CV in English"
            ),
        ),
        migrations.AddField(
            model_name="aboutme",
            name="cv_nl",
            field=models.FileField(
                blank=True, null=True, upload_to="cv/", verbose_name="CV in Dutch"
            ),
        ),
    ]
