# Generated by Django 4.2.25 on 2026-05-06 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_AboutMe", "0003_alter_aboutme_cv_en_alter_aboutme_cv_nl_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutme",
            options={"verbose_name": "About Me", "verbose_name_plural": "About Me"},
        ),
    ]
